// DEFANGED: static-analysis cache — do not execute
throw new Exception('DEFANGED: static-analysis cache — do not execute')
plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.paywallsdk'
version = '0.1.0'

android {
  namespace "expo.modules.paywallsdk"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("com.tryhelium.paywall:core:4.4.7")
  implementation("com.google.code.gson:gson:2.10.1")
  implementation("com.android.billingclient:billing:8.0.0")
}
