// DEFANGED: static-analysis cache — do not execute
throw new Exception('DEFANGED: static-analysis cache — do not execute')
apply plugin: 'com.android.library'

group = 'io.weavr.reactnative.components'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

// Add repositories for dependencies
repositories {
  google()
  mavenCentral()
  maven { url "https://maven.sumsub.com/repository/maven-public/" }
  maven { url "https://www.jitpack.io" }
  maven { url "https://gitlab.okaythis.com/api/v4/projects/15/packages/maven"; name "GitLab" }
}

// If you want to use the managed Android SDK versions from expo-modules-core, set this to true.
// The Android SDK versions will be bumped from time to time in SDK releases and may introduce breaking changes in your module code.
// Most of the time, you may like to manage the Android SDK versions yourself.
def useManagedAndroidSdkVersions = false
if (useManagedAndroidSdkVersions) {
  useDefaultAndroidSdkVersions()
} else {
  buildscript {
    // Simple helper that allows the root project to override versions declared by this library.
    ext.safeExtGet = { prop, fallback ->
      rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
    }
  }
  project.android {
    compileSdkVersion safeExtGet("compileSdkVersion", 36)
    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 24)
      targetSdkVersion safeExtGet("targetSdkVersion", 36)
    }
  }
}

android {
  namespace "io.weavr.reactnative.components"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // When updating this version, also update getSDKVersion in the native module and the version in plugin/src/withAndroidInjectedLocalRepo.ts.
  implementation 'io.weavr.components:secure-components:3.11.0'
}
