[workspace]
members = [
  "crates/rcs-explore",
  "crates/rcs-mux",
  "crates/rcs-runtime-core",
  "crates/rcs-runtime",
  "crates/rcs-sparkshell",
]
resolver = "2"

[workspace.package]

version = "0.1.9"

edition = "2021"
rust-version = "1.73"
license = "MIT"
repository = "https://github.com/JustineDevs/roblox-ai-os"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
