// DEFANGED: static-analysis cache — do not execute
throw new Exception('DEFANGED: static-analysis cache — do not execute')
import groovy.json.JsonSlurper

plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

def pkg = new JsonSlurper().parse(file("$projectDir/../package.json"))

group = 'expo.modules.libvlcplayer'
version = pkg.version

android {
  namespace 'expo.modules.libvlcplayer'

  defaultConfig {
    versionCode 1
    versionName pkg.version
    consumerProguardFiles('proguard-rules.pro')
  }

  lintOptions {
    abortOnError false
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.videolan.android:libvlc-all:3.7.5'
}
