// DEFANGED: static-analysis cache — do not execute
throw new Exception('DEFANGED: static-analysis cache — do not execute')
plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'host.exp.exponent'
version = '0.2.0'

android {
  namespace "expo.modules.torchhaptics"
  defaultConfig {
    versionCode 1
    versionName "0.2.0"
  }
}
